### ISSUE TITLE
Install MongoDB locally on your PC

### ISSUE THREAD

**Issue by smokejohn** [spielstART/match-system#13]
**everyone** should install mongoDB **locally**, i dont want to push files with up to 20MB or way more into the master branch.

If you want to test the app, fire up mongoDB
`mongod --dbpath "c:\mongo\test\" (adjust path to your liking)`

then start the node app via:
`node app.js`

works as long as node is in your path variable, and thus globally available and you're in the directory containing the match-system app.js

Express app connects automatically as long as your mongoDB runs on the standard port (27017)

**Comment by noxan** [comment]
Works fine, we should just remove the node dependencies from the repo (everyone can install them via npm himself).

**Comment by smokejohn** [comment]
Done, deleted node_modules and added the folder to the .gitignore so you all can push without having to worry about the modules.

If you pull now, you have to first fire up CMD/Terminal and type `npm install` while in your node app folder

**Comment by noxan** [comment]
Guess it's up to everyone to setup his database, so I'll close this issue.
